# Main Orchestrator Docker Compose File
services:
  # loadbalancer:
  #   extends:
  #     file: ./1_load_balancer/nginx/docker-compose.yaml
  #     service: nginx

  # auth:
  #   extends:
  #     file: ./2_auth_layer/keycloak/docker-compose.yaml
  #     service: keycloak

  # app:
  #   extends:
  #     file: ./3_app_layer/backend/docker-compose.yaml
  #     service: backend

  keycloak:
    extends:
      file: ./2_auth_layer/docker-compose.yaml
      service: keycloak

  db:
    extends:
      file: ./db_layer/docker-compose.yaml
      service: db

  pgadmin:
    extends:
      file: ./db_layer/docker-compose.yaml
      service: pgadmin 

networks:
  app_network:
    driver: bridge

volumes:
  db-data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: ./db_layer/data/db-data
      o: bind

  pgadmin-data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: ./db_layer/data/pgadmin-data
      o: bind
